#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# compile_example.sh – Verify that the MAX17055 component compiles with ESPHome
#
# Usage:
#   ./scripts/compile_example.sh [yaml_file]
#   ./scripts/compile_example.sh examples/esp32-example.yaml
#   ./scripts/compile_example.sh examples/esp32-deep-sleep-example.yaml
#
# Default: compiles both examples in sequence.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${REPO_ROOT}/.venv"
SECRETS_FILE="${REPO_ROOT}/secrets.yaml"
ESPHOME_VERSION_REQ="2024.6"  # minimum: DEVICE_CLASS_DURATION + current sensor_schema API

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[OK]${NC}  $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERR]${NC}  $*" >&2; }

echo "──────────────────────────────────────────────────────────────"
echo " MAX17055 ESPHome Compile Check"
echo " Repo: ${REPO_ROOT}"
echo "──────────────────────────────────────────────────────────────"

# ── Python check ─────────────────────────────────────────────────────────────
PYTHON=$(command -v python3 || command -v python || true)
if [[ -z "${PYTHON}" ]]; then
  err "Python 3 not found.  Install Python 3.9+ and rerun."
  exit 1
fi
PYVER=$("${PYTHON}" -c "import sys; print('.'.join(map(str,sys.version_info[:3])))")
ok "Python ${PYVER} at ${PYTHON}"

# ── Virtual environment ───────────────────────────────────────────────────────
if [[ ! -d "${VENV_DIR}" ]]; then
  echo "Creating virtual environment in ${VENV_DIR} ..."
  "${PYTHON}" -m venv "${VENV_DIR}"
fi

# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
ok "Activated venv: ${VENV_DIR}"

# ── ESPHome install / upgrade ─────────────────────────────────────────────────
if ! command -v esphome &>/dev/null; then
  echo "Installing ESPHome (latest) ..."
  pip install --quiet --upgrade pip
  pip install --quiet esphome
else
  INSTALLED_VER=$(esphome version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+' | head -1 || echo "0.0")
  ok "ESPHome ${INSTALLED_VER} already installed"
  # Uncomment to always upgrade:
  # pip install --quiet --upgrade esphome
fi

# ── Version check ─────────────────────────────────────────────────────────────
ESPHOME_VER=$(esphome version 2>/dev/null | head -1)
INSTALLED_YEAR=$(esphome version 2>/dev/null | grep -oE '[0-9]{4}\.[0-9]+' | head -1 | cut -d. -f1 || echo "0")
INSTALLED_MON=$(esphome  version 2>/dev/null | grep -oE '[0-9]{4}\.[0-9]+' | head -1 | cut -d. -f2 || echo "0")
REQ_YEAR=$(echo "${ESPHOME_VERSION_REQ}" | cut -d. -f1)
REQ_MON=$(echo  "${ESPHOME_VERSION_REQ}" | cut -d. -f2)
if [[ ${INSTALLED_YEAR} -lt ${REQ_YEAR} ]] || \
   [[ ${INSTALLED_YEAR} -eq ${REQ_YEAR} && ${INSTALLED_MON} -lt ${REQ_MON} ]]; then
  err "ESPHome ${INSTALLED_YEAR}.${INSTALLED_MON} is older than required ${ESPHOME_VERSION_REQ}"
  err "Run: pip install --upgrade esphome"
  exit 1
fi
ok "Using: ${ESPHOME_VER}"
echo "Python: ${PYVER}"
echo ""

# ── Synthetic secrets.yaml ────────────────────────────────────────────────────
# Real credentials are not needed for a compile-only check.
if [[ ! -f "${SECRETS_FILE}" ]]; then
  cat > "${SECRETS_FILE}" <<'SECRETS_EOF'
# Auto-generated by compile_example.sh – safe placeholder values for compilation
wifi_ssid: "compile_test_ssid"
wifi_password: "compile_test_password"
api_encryption_key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
ota_password: "compile_test"
SECRETS_EOF
  warn "Created placeholder ${SECRETS_FILE} (safe for compilation only)"
fi

# ── Build cache directory ─────────────────────────────────────────────────────
BUILD_DIR="${REPO_ROOT}/.esphome_build"
mkdir -p "${BUILD_DIR}"

# ── Compile function ──────────────────────────────────────────────────────────
compile_yaml() {
  local yaml_file="$1"
  local yaml_abs="${REPO_ROOT}/${yaml_file}"

  if [[ ! -f "${yaml_abs}" ]]; then
    err "YAML not found: ${yaml_abs}"
    return 1
  fi

  echo ""
  echo "── Compiling: ${yaml_file} ─────────────────────────────────────"

  # esphome compile runs from the repo root so that:
  #   • external_components path: ../components resolves correctly
  #   • secrets.yaml is found in the CWD
  (
    cd "${REPO_ROOT}"
    esphome \
      --config-dir "${BUILD_DIR}" \
      compile "${yaml_abs}"
  )

  local rc=$?
  if [[ ${rc} -eq 0 ]]; then
    ok "${yaml_file} compiled successfully"
  else
    err "${yaml_file} FAILED (exit code ${rc})"
    return ${rc}
  fi
}

# ── Main ──────────────────────────────────────────────────────────────────────
EXAMPLES=(
  "examples/esp32-example.yaml"
  "examples/esp32-deep-sleep-example.yaml"
)

if [[ $# -gt 0 ]]; then
  # User specified a file
  compile_yaml "$1"
else
  PASS=0; FAIL=0
  for ex in "${EXAMPLES[@]}"; do
    if compile_yaml "${ex}"; then
      PASS=$((PASS+1))
    else
      FAIL=$((FAIL+1))
    fi
  done

  echo ""
  echo "══════════════════════════════════════════════════════════════"
  echo " Results: ${PASS} passed / ${FAIL} failed"
  echo " ESPHome : ${ESPHOME_VER}"
  echo " Python  : ${PYVER}"
  echo "══════════════════════════════════════════════════════════════"

  if [[ ${FAIL} -gt 0 ]]; then
    exit 1
  fi
fi
